name: R dependency checks

# This workflow is intended to check that the latest release of the cellxgene.census R package
# continues to function correctly using the latest upstream dependencies.

on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch: # used for debugging or manual validation
  pull_request: # Used for testing

jobs:
  r-dependency-check:
    name: r-dependency-check

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{matrix.os}}

    steps:
      - uses: r-lib/actions/setup-r@v2
      - name: install cellxgene.census and dependencies
        # This should follow our user-facing instructions to install cellxgene.census.
        run: Rscript -e "install.packages(c('cellxgene.census', 'testthat'), repos=c('https://chanzuckerberg.r-universe.dev', 'https://cloud.r-project.org'), type='source')"
      - name: run unit tests
        # cd to the cellxgene.census installed package directory, and run its tests
        run: |
            cd "$(Rscript -e 'cat(system.file(package="cellxgene.census"))')"/tests
            Rscript testthat.R
