name: R dependency checks

# This workflow is intended to check that the latest release of the cellxgene.census R package
# continues to function correctly using the latest upstream dependencies.

on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch: # used for debugging or manual validation
  pull_request: # Used for testing

jobs:
  r-dependency-check:
    name: r-dependency-check

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{matrix.os}}

    steps:
      - uses: r-lib/actions/setup-r@v2
      - name: install cellxgene.census and dependencies
        # This should follow our user-facing instructions to install cellxgene.census.
        run: |
            Rscript -e 'install.packages(c("cellxgene.census", "Seurat", "BiocManager", "testthat"), repos=c("https://chanzuckerberg.r-universe.dev", "https://cloud.r-project.org"))'
            Rscript -e 'BiocManager::install("SingleCellExperiment")'
      - name: run unit tests
        # [re-]fetch the cellxgene.census source package which includes the unit test code to run
        run: |
            set -ex
            Rscript -e 'download.packages("cellxgene.census", destdir=".", repos="https://chanzuckerberg.r-universe.dev", type="source")'
            tar zxf cellxgene.census_*.tar.gz
            cd cellxgene.census/tests
            Rscript testthat.R
