name: cell_census R package checks

on:
  pull_request:
    paths-ignore:
      - "apis/python/**"
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: ./api/r/cellcensus
          extra-packages: any::rcmdcheck, any::styler
          needs: check
      - name: styler
        run: Rscript -e 'style_pkg("api/r/cellcensus", dry="fail")'
      - uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: ./api/r/cellcensus
          args: 'c("--no-manual", "--as-cran")'
